### ISSUE TITLE
Taro v3.6.8  taro tailwind --init 失败

### ISSUE THREAD

**Issue by oberdex** [pcdotfan/taro-plugin-tailwind#229]
👽 Taro v3.6.8

Error: Cannot find module './dist/index.js'
Require stack:
- D:\WWW\jz.test\app\tt\node_modules\taro-plugin-tailwind\index.js
- D:\WWW\jz.test\app\tt\node_modules\@tarojs\service\dist\utils\index.js
- D:\WWW\jz.test\app\tt\node_modules\@tarojs\service\dist\Kernel.js
- D:\WWW\jz.test\app\tt\node_modules\@tarojs\service\dist\index.js
- D:\WWW\jz.test\app\tt\node_modules\@tarojs\service\index.js
- D:\WWW\jz.test\app\tt\node_modules\@tarojs\cli\dist\cli.js
- D:\WWW\jz.test\app\tt\node_modules\@tarojs\cli\bin\taro
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (D:\WWW\jz.test\app\tt\node_modules\taro-plugin-tailwind\index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.newLoader [as .js] (D:\WWW\jz.test\app\tt\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
  code: 'MODULE_NOT_FOUND',

NODE:v16.20.1
平台:windows

**Comment by pcdotfan** [comment]
抱歉打包出了点问题，麻烦下载 1.3.3 重试。

**Comment by oberdex** [comment]
D:\tt\WWW\jz.test\app\tuotiao2\node_modules\taro-plugin-tailwind\dist\chain.js:7
const checkConfigExists = (platform) => (0, fs_extra_1.existsSync)(path_1.default.resolve(getConfigPath(platform)));
                                                                                  ^

TypeError: Cannot read properties of undefined (reading 'resolve')

**Comment by oberdex** [comment]
> [Release 1.3.4](https://github.com/pcdotfan/taro-plugin-tailwind/releases/tag/v1.3.4)
谢谢 ok了
