### ISSUE TITLE
执行 taro tailwind --init 生成配置文件报错

### ISSUE THREAD

**Issue by lanxuexing** [pcdotfan/taro-plugin-tailwind#93]
### 1. config/index.js

```js
const config = {
  projectName: "mini",
  date: "2022-4-16",
  designWidth: 750,
  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2,
  },
  sourceRoot: "src",
  outputRoot: "dist",
  plugins: ['taro-plugin-tailwind'],
  defineConstants: {},
  copy: {
    patterns: [],
    options: {},
  },
  framework: "react",
  mini: {
    postcss: {
      pxtransform: {
        enable: true,
        config: {},
      },
      url: {
        enable: true,
        config: {
          limit: 1024, // 设定转换尺寸上限
        },
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: "module", // 转换模式，取值为 global/module
          generateScopedName: "[name]__[local]___[hash:base64:5]",
        },
      },
    },
  },
  h5: {
    publicPath: "/",
    staticDirectory: "static",
    postcss: {
      autoprefixer: {
        enable: true,
        config: {},
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: "module", // 转换模式，取值为 global/module
          generateScopedName: "[name]__[local]___[hash:base64:5]",
        },
      },
    },
  },
};

module.exports = function (merge) {
  if (process.env.NODE_ENV === "development") {
    return merge({}, config, require("./dev"));
  }
  return merge({}, config, require("./prod"));
};

```

### 2. package.json
```json
{
  "name": "mini",
  "version": "1.0.0",
  "private": true,
  "description": "mini",
  "templateInfo": {
    "name": "taro-hooks",
    "typescript": true,
    "css": "sass"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/cli": "3.4.6",
    "@tarojs/components": "3.4.6",
    "@tarojs/plugin-framework-react": "3.4.6",
    "@tarojs/react": "3.4.6",
    "@tarojs/runtime": "3.4.6",
    "@tarojs/taro": "3.4.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "taro-hooks": "latest"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/mini-runner": "3.4.6",
    "@tarojs/webpack-runner": "3.4.6",
    "@types/react": "^17.0.2",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "babel-plugin-import": "^1.13.3",
    "babel-preset-taro": "3.4.6",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.4.6",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "stylelint": "9.3.0",
    "taro-plugin-tailwind": "^1.2.8",
    "typescript": "^4.2.3"
  },
  "engines": {
    "node": ">=12.0.0"
  }
}

```

### 3. 终端命令
```vim
▶ taro tailwind --init
👽 Taro v3.4.6

/Users/apple/Desktop/mini/node_modules/taro-plugin-tailwind/dist/chain.js:11
    ctx.onBuildStart(() => {
        ^

TypeError: ctx.onBuildStart is not a function
    at exports.default (/Users/apple/Desktop/mini/node_modules/taro-plugin-tailwind/src/chain.ts:23:9)
    at exports.default (/Users/apple/Desktop/mini/node_modules/taro-plugin-tailwind/src/index.ts:8:23)
    at Kernel.initPlugin (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:111:16)
    at Kernel.resolvePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:86:18)
    at Kernel.initPresetsAndPlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:74:14)
    at Kernel.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:261:18)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:4:12)

~/Desktop/mini  master ✗  
```

> 想问一下是依赖按照问题吗？我这边按照`README`文件的步骤来的，但是无法生成配置文件

**Comment by lanxuexing** [comment]
貌似是`Taro`脚手架的问题：[版本号 3.4.6 报错 ctx.onBuildStart is not a function](https://github.com/NervJS/taro/issues/11646)

我回退了一下成功了，终端命令如下：
```vim
$ mini % 
$ mini % npx @tarojs/cli@3.4.4 tailwind --init
👽 Taro v3.4.4

[taro-plugin-tailwind] File .taro-plugin-tailwind/mini.config.js has been created.
[taro-plugin-tailwind] File .taro-plugin-tailwind/h5.config.js has been created.
$ mini %      
```

**Comment by Chen-jj** [comment]
https://github.com/NervJS/taro/pull/11662
